{
    "name": "ForexManager: Cambio de divisas",
    "version": "1.0",
    "category": "Currency exchange",
    "summary": "Gestión para empresas orientadas al cambio de divisas ",
    "author": "Jeffry Hernández",
    "depends": ["base", "web",],
    # "assets": {
    #     "web.assets_backend": [
    #         "forexmanager/static/src/js/notebook_scroll.js",
    #         ],
    #     },
    "data": [
        "security/forexmanager_security.xml",
        "security/ir.model.access.csv",
        "views/calculation_views.xml",
        "views/customer_views.xml",
        "views/operation_views.xml",
        "views/currency_views.xml",
        "views/cashcount_views.xml",
        "views/desk_views.xml",
        "views/workcenter_views.xml",
        "views/worksession_views.xml",
        "views/currentdesktransient_views.xml",
        "views/checkbalance_views.xml",
        "views/transfer_line_views.xml",
        "views/transfer_views.xml",
        "views/transfer_admin_views.xml",
        "views/transfer_line_currency_views.xml",
        # "views/transfer_transient_views.xml",
        "views/menu_views.xml", 
    ],
    "post_init_hook": "initial_config",
    "installable": True,
    "application": True,
}